### ISSUE TITLE
Färg på hjärtan i mobilläge

### ISSUE THREAD

**Issue by crippe** [knowit/program.kds.knowit.no#4]
Är det möjligt att få gråa hjärtan i mobilt läge, när man inte markerat en presentation?

 Från iOS:
![image1](https://user-images.githubusercontent.com/8159400/35121013-48300944-fc9a-11e7-8b08-c7a740429cc6.png)

Från desktop:
<img width="227" alt="screen shot 2018-01-18 at 21 56 05" src="https://user-images.githubusercontent.com/8159400/35121057-73582b7e-fc9a-11e7-87c4-a7e4384af020.png">

**Comment by Maritt** [comment]
closing as this is no longer relevant with new design
